# Generated by Django 2.2.5 on 2020-05-15 19:02

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('calories', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('serving_size', models.CharField(max_length=50)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
            ],
            managers=[
                ('food', django.db.models.manager.Manager()),
            ],
        ),
    ]
