# Generated by Django 2.2.5 on 2020-05-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fats',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
