# Generated by Django 2.2.5 on 2020-05-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodyApp', '0002_auto_20200515_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='serving_size',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
